name = "chargily-mcp"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "ChargilyMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChargilyMCP"]

[[routes]]
pattern = "mcp.ta9in.com/chargily-mcp*"
zone_name = "ta9in.com"
